## Data Extraction

In [1]:
# Import necessary libraries
import pandas as pd
import os

# Define function to extract specific columns
def extract_columns(input_file, output_file, columns_to_keep, columns_rename={}):
    """
    Extract specific columns from a CSV file and save to a new CSV file.
    
    Parameters:
    input_file (str): Path to the input CSV file
    output_file (str): Path to save the output CSV file
    columns_to_keep (list): List of column names to keep
    columns_rename (dict): Dictionary mapping original column names to new names
    
    Returns:
    DataFrame: The extracted data
    """
    try:
        # Read the CSV file
        df = pd.read_csv(input_file)
        
        # Display the first few rows of the original dataframe
        print("First 5 rows of the original dataframe:")
        display(df.head())
        
        # Print all column names for reference
        print("\nAll columns in the CSV file:")
        print(df.columns.tolist())
        
        # Check if all specified columns exist in the dataframe
        missing_columns = [col for col in columns_to_keep if col not in df.columns]
        if missing_columns:
            print(f"\nWarning: The following columns were not found in the CSV: {missing_columns}")
            # Filter out missing columns
            columns_to_keep = [col for col in columns_to_keep if col in df.columns]
            
        if not columns_to_keep:
            print("Error: None of the specified columns were found in the CSV file.")
            return None
            
        # Select only the specified columns
        df_selected = df[columns_to_keep]
        
        # Rename columns if specified
        if columns_rename:
            # Filter out any rename mappings for columns that don't exist
            valid_renames = {old: new for old, new in columns_rename.items() if old in df_selected.columns}
            if valid_renames:
                df_selected = df_selected.rename(columns=valid_renames)
                print("\nRenamed the following columns:")
                for old, new in valid_renames.items():
                    print(f"  {old} -> {new}")
            
            # Check for invalid rename mappings
            invalid_renames = {old: new for old, new in columns_rename.items() if old not in df_selected.columns}
            if invalid_renames:
                print("\nWarning: Could not rename the following columns (not found in selection):")
                for old, new in invalid_renames.items():
                    print(f"  {old} -> {new}")
        
        # Display the first few rows of the new dataframe
        print("\nFirst 5 rows of the extracted dataframe:")
        display(df_selected.head())
        
        # Save the selected columns to a new CSV file
        df_selected.to_csv(output_file, index=False)
        
        print(f"\nSuccessfully extracted {len(columns_to_keep)} columns to {output_file}")
        return df_selected
        
    except Exception as e:
        print(f"Error: {str(e)}")
        return None

In [2]:
# Configuration cells - modify these values
input_file = "data/children_2015.csv"  # Replace with your actual input file path
output_file = "exports/children_extr_2015.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "h22",
    # "ml13e",	
    "v001",	
    "v021",	
    "v024",	
    "v025",	
    "b5",	
    "b8",	
    "ml0",
]

column_rename_dict = {
    "h22": "treat_src",     # Source of treatment
    # "ml13e": "act_used",    # ACT use (Antimalarial)
    "v001": "cluster",      # Cluster number
    "v021": "stratum",      # Sample stratum
    "v024": "region",       # Region
    "v025": "residence",    # Urban/rural
    "b5": "alive",          # Child alive
    "b8": "age_mo",         # Age in months
    "ml0": "fever_rec"      # Fever recall
}


# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_rename_dict)

First 5 rows of the original dataframe:

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2086272929.py:21: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

,caseid,hidx,v000,v001,v002,v003,v004,v005,v006,v007,...,sv112g,sv112h,sv112i,sv112j,sv112k,sv112l,sv112m,sv112n,sv112o,sv112p
0,001027 02,1,KE6,1,27,2,1,6074405,7,2015,...,no,yes,yes,yes,no,no,no,no,yes,yes
1,001027 02,2,KE6,1,27,2,1,6074405,7,2015,...,no,yes,yes,yes,no,no,no,no,yes,yes
2,001048 02,1,KE6,1,48,2,1,6074405,7,2015,...,no,yes,yes,yes,yes,no,no,no,no,yes
3,001048 02,2,KE6,1,48,2,1,6074405,7,2015,...,no,yes,yes,yes,yes,no,no,no,no,yes
4,001076 02,1,KE6,1,76,2,1,6074405,7,2015,...,no,yes,yes,yes,yes,yes,no,no,yes,yes

All columns in the CSV file:
['caseid', 'hidx', 'v000', 'v001', 'v002', 'v003', 'v004', 'v005', 'v006', 'v007', 'v008', 'v009', 'v010', 'v011', 'v012', 'v013', 'v014', 'v015', 'v016', 'v017', 'v018', 'v019', 'v019a', 'v020', 'v021', 'v022', 'v023', 'v024', 'v025', 'v026', 'v027', 'v028', 'v029', 'v030', 'v031', 'v032', 'v034', 'v040', 'v042', 'v044', 'v101', 'v102', 'v103', 'v104', 'v105', 'v106', 'v107', 'v113', 'v115', 'v116', 'v119', 'v120', 'v121', 'v122', 'v123', 'v124', 'v125', 'v127', 'v128', 'v129', 'v130', 'v131', 'v133', 'v134', 'v135', 'v136', 'v137', 'v138', 'v139', 'v140', 'v141', 'v149', 'v150', 'v151', 'v152', 'v153', 'awfactt', 'awfactu', 'awfactr', 'awfacte', 'awfactw', 'v155', 'v156', 'v157', 'v158', 'v159', 'v160', 'v161', 'v166', 'v167', 'v168', 'v190', 'v191', 'ml101', 'v201', 'v202', 'v203', 'v204', 'v205', 'v206', 'v207', 'v208', 'v209', 'v210', 'v211', 'v212', 'v213', 'v214', 'v215', 'v216', 'v217', 'v218', 'v219', 'v220', 'v221', 'v222', 'v223', 'v224', 'v225', 'v226', 'v227', 'v228', 'v229', 'v230', 'v231', 'v232', 'v233', 'v234', 'v235', 'v237', 'v238', 'v239', 'v240', 'v241', 'v242', 'v243', 'bidx', 'bord', 'b0', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'b10', 'b11', 'b12', 'b13', 'b15', 'b16', 's216d', 'midx', 'm2a', 'm2b', 'm2c', 'm2d', 'm2e', 'm2f', 'm2g', 'm2h', 'm2i', 'm2j', 'm2k', 'm2l', 'm2m', 'm2n', 'm14', 'm49a', 'h22', 'h31', 'h31b', 'h31c', 'h31d', 'h31e', 'h32a', 'h32b', 'h32c', 'h32d', 'h32e', 'h32f', 'h32g', 'h32h', 'h32i', 'h32j', 'h32k', 'h32l', 'h32m', 'h32n', 'h32o', 'h32p', 'h32q', 'h32r', 'h32s', 'h32t', 'h32u', 'h32v', 'h32w', 'h32x', 'h32y', 'h32z', 'h37a', 'h37b', 'h37c', 'h37d', 'h37e', 'h37f', 'h37g', 'h37h', 'h37i', 'h37j', 'h37k', 'h37l', 'h37m', 'h37n', 'h37o', 'h37p', 'h37x', 'h37y', 'h37z', 'h46a', 'h46b', 'h47', 'idxml', 'ml0', 'ml1', 'ml2', 'ml11', 'ml12', 'ml13a', 'ml13b', 'ml13c', 'ml13d', 'ml13e', 'ml13f', 'ml13g', 'ml13h', 'ml13i', 'ml13j', 'ml13k', 'ml13l', 'ml13m', 'ml13n', 'ml13o', 'ml13p', 'ml13x', 'ml13y', 'ml13z', 'ml14a', 'ml14b', 'ml14y', 'ml14z', 'ml15a', 'ml15b', 'ml15c', 'ml16a', 'ml16b', 'ml16c', 'ml17a', 'ml17b', 'ml17c', 'ml18a', 'ml18b', 'ml18c', 'ml19a', 'ml19b', 'ml19c', 'ml19d', 'ml19e', 'ml19f', 'ml19x', 'ml19y', 'ml19z', 'ml20a', 'ml20b', 'ml20c', 'ml21a', 'ml21b', 'ml21c', 'ml22a', 'ml22b', 'ml22c', 'ml23a', 'ml23b', 'ml23c', 'ml24c', 's411a', 's411b', 's411c', 'ml25a', 's412b', 'scounty', 'szone', 'slang', 'slangint', 'stransl', 's105', 's106', 's111', 's112a', 's112b', 's112c', 's112d', 's112e', 's112f', 's427b', 's427c', 's427d', 's427e', 's427f1', 's427f2', 's427f3', 's427f4', 's427f5', 's427f6', 's427f7', 's427f8', 's427f9', 'sv112e', 'sv112g', 'sv112h', 'sv112i', 'sv112j', 'sv112k', 'sv112l', 'sv112m', 'sv112n', 'sv112o', 'sv112p']

Renamed the following columns:
  h22 -> treat_src
  v001 -> cluster
  v021 -> stratum
  v024 -> region
  v025 -> residence
  b5 -> alive
  b8 -> age_mo
  ml0 -> fever_rec

Warning: Could not rename the following columns (not found in selection):
  h22 -> treat_src
  v001 -> cluster
  v021 -> stratum
  v024 -> region
  v025 -> residence
  b5 -> alive
  b8 -> age_mo
  ml0 -> fever_rec

First 5 rows of the extracted dataframe:

,treat_src,cluster,stratum,region,residence,alive,age_mo,fever_rec
0,no,1,1,nairobi,urban,yes,2.0,only treated nets
1,no,1,1,nairobi,urban,yes,3.0,only treated nets
2,yes,1,1,nairobi,urban,yes,1.0,only treated nets
3,no,1,1,nairobi,urban,yes,3.0,only treated nets
4,yes,1,1,nairobi,urban,yes,4.0,NaN

Successfully extracted 8 columns to exports/children_extr_2015.csv

In [3]:
# Configuration cells - modify these values
input_file = "data/children_2020.csv"  # Replace with your actual input file path
output_file = "exports/children_extr_2020.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "h22",
    "ml0",	
    "b5",	
    "b8",	
    # "ml13aa",	
    # "ml13ab",
    "v001",
    "v021",
    "v024",
    "v025"
]

column_names = {
    "h22": "treat_src",
    "ml0": "fever_rec",
    "b5": "alive",
    "b8": "age_mo",
    # "ml13aa": "net1",
    # "ml13ab": "net2",
    "v001": "cluster",
    "v021": "stratum",
    "v024": "region",
    "v025": "residence"
}



# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_names)

First 5 rows of the original dataframe:

,caseid,hidxa,v000,v001,v002,v003,v004,v005,v006,v007,...,s307a,s309ba,s309bb,s309bc,s309bd,s309be,s309bf,s309bg,s309bx,s309bz
0,2 1 2,1,KE7,2,1,2,2,607390,12,2020,...,spouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2 1 2,2,KE7,2,1,2,2,607390,12,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2 6 2,1,KE7,2,6,2,2,607390,11,2020,...,respondent,no,no,no,no,no,no,no,yes,no
3,2 6 2,2,KE7,2,6,2,2,607390,11,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2 10 2,1,KE7,2,10,2,2,607390,11,2020,...,respondent,no,no,no,no,no,yes,no,no,no

All columns in the CSV file:
['caseid', 'hidxa', 'v000', 'v001', 'v002', 'v003', 'v004', 'v005', 'v006', 'v007', 'v008', 'v008a', 'v009', 'v010', 'v011', 'v012', 'v013', 'v014', 'v015', 'v016', 'v021', 'v022', 'v023', 'v024', 'v025', 'v026', 'v027', 'v028', 'v029', 'v030', 'v031', 'v032', 'v034', 'v040', 'v042', 'v045a', 'v045b', 'v045c', 'v046', 'v101', 'v102', 'v106', 'v107', 'v113', 'v115', 'v116', 'v119', 'v120', 'v121', 'v122', 'v123', 'v124', 'v125', 'v127', 'v128', 'v129', 'v130', 'v131', 'v133', 'v134', 'v135', 'v136', 'v137', 'v138', 'v139', 'v140', 'v141', 'v149', 'v150', 'v151', 'v152', 'v153', 'v155', 'v157', 'v158', 'v159', 'v160', 'v161', 'v169a', 'v171a', 'v171b', 'v190', 'v191', 'v190a', 'v191a', 'ml101', 'v201', 'v202', 'v203', 'v204', 'v205', 'v206', 'v207', 'v208', 'v209', 'v210', 'v213', 'v214', 'v218', 'v219', 'v220', 'v222', 'v223', 'v224', 'v237', 'v238', 'v417', 'v418a', 'v419', 'v459', 'v460', 'v461', 'v468', 'bidx', 'bord', 'b0', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'b10', 'b11', 'b12', 'b13', 'b15', 'b16', 'b17', 'b18', 'b19', 'midx', 'm2a', 'm2b', 'm2c', 'm2d', 'm2e', 'm2f', 'm2g', 'm2h', 'm2i', 'm2j', 'm2k', 'm2l', 'm2m', 'm2n', 'm13', 'm14', 'm49a', 'm49b', 'm49c', 'm49d', 'm49e', 'm49f', 'm49g', 'm49x', 'm49z', 'm49y', 'm57a', 'm57b', 'm57c', 'm57d', 'm57e', 'm57f', 'm57g', 'm57h', 'm57i', 'm57j', 'm57k', 'm57l', 'm57m', 'm57n', 'm57o', 'm57p', 'm57q', 'm57r', 'm57s', 'm57t', 'm57u', 'm57v', 'm57x', 'h22', 'h31', 'h32a', 'h32b', 'h32c', 'h32d', 'h32e', 'h32f', 'h32g', 'h32h', 'h32i', 'h32j', 'h32k', 'h32l', 'h32m', 'h32n', 'h32o', 'h32p', 'h32q', 'h32r', 'h32s', 'h32t', 'h32u', 'h32v', 'h32w', 'h32x', 'h32y', 'h32z', 'h46a', 'h46b', 'h47', 's406', 'hwidx', 'hw1', 'hw16', 'hw17', 'hw18', 'hw19', 'hw51', 'hw52', 'hw53', 'hw55', 'hw56', 'hw57', 'hw58', 'v801', 'v802', 'v803', 'v804', 'v805', 'v806', 'idxml', 'ml0', 'ml1', 'ml2', 'ml11', 'ml12', 'ml13a', 'ml13b', 'ml13c', 'ml13d', 'ml13da', 'ml13e', 'ml13aa', 'ml13ab', 'ml13f', 'ml13g', 'ml13h', 'ml13i', 'ml13j', 'ml13k', 'ml13l', 'ml13m', 'ml13n', 'ml13o', 'ml13p', 'ml13x', 'ml13y', 'ml13z', 'ml14a', 'ml14b', 'ml14y', 'ml14z', 'ml15a', 'ml15b', 'ml15c', 'ml16a', 'ml16b', 'ml16c', 'ml17a', 'ml17b', 'ml17c', 'ml18a', 'ml18b', 'ml18c', 'ml19a', 'ml19b', 'ml19c', 'ml19d', 'ml19e', 'ml19f', 'ml19x', 'ml19y', 'ml19z', 'ml20a', 'ml20b', 'ml20c', 'ml21a', 'ml21b', 'ml21c', 'ml22a', 'ml22b', 'ml22c', 'ml23a', 'ml23b', 'ml23c', 'ml24c', 'ml25a', 's413a', 's413b', 's413c', 'scounty', 'szone', 's114', 's211', 's225', 's501', 's502a', 's502b', 's502c', 's502d', 's502e', 's502f', 's502g', 's502h', 's502i', 's502j', 's502k', 's502l', 's502m', 's502x', 's502z', 's502aa', 's502ab', 's502ac', 's502ad', 's502ae', 's502af', 's502ag', 's502ax', 's502az', 's503', 's504a', 's504b', 's504c', 's504d', 's504e', 's504f', 's504g', 's504h', 's504i', 's504x', 's504z', 's504aa', 's504ab', 's504ac', 's504ad', 's504ax', 's504az', 's505', 's506', 's507', 's508', 's509', 's510', 's511', 's511a', 's512', 's513', 's514', 's514a', 's514ba', 's514bb', 's514bc', 's514bd', 's514bx', 's514bz', 'idx94', 's306', 's307a', 's309ba', 's309bb', 's309bc', 's309bd', 's309be', 's309bf', 's309bg', 's309bx', 's309bz']

Renamed the following columns:
  h22 -> treat_src
  ml0 -> fever_rec
  b5 -> alive
  b8 -> age_mo
  v001 -> cluster
  v021 -> stratum
  v024 -> region
  v025 -> residence

Warning: Could not rename the following columns (not found in selection):
  h22 -> treat_src
  ml0 -> fever_rec
  b5 -> alive
  b8 -> age_mo
  v001 -> cluster
  v021 -> stratum
  v024 -> region
  v025 -> residence

First 5 rows of the extracted dataframe:

,treat_src,fever_rec,alive,age_mo,cluster,stratum,region,residence
0,yes,no net,yes,0.0,2,2,coast,rural
1,no,only treated nets,yes,4.0,2,2,coast,rural
2,no,no net,yes,2.0,2,2,coast,rural
3,no,no net,yes,3.0,2,2,coast,rural
4,yes,only treated nets,yes,0.0,2,2,coast,rural

Successfully extracted 8 columns to exports/children_extr_2020.csv

In [4]:
# Configuration cells - modify these values
input_file = "data/household_member-2015.csv"  # Replace with your actual input file path
output_file = "exports/household_member-extr_2015.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "hml12",
    "hml20",	
    "hv001",	
    "hv024",	
    "hv021",	
    "hv025",
]

column_rename_dict = {
    "hml12": "net_owned",    # Number of mosquito nets owned
    "hml20": "net_used",     # Used net last night
    "hv001": "cluster",      # Cluster number
    "hv024": "region",       # Region
    "hv021": "stratum",      # Sample stratum
    "hv025": "residence"     # Urban/rural
}




# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_rename_dict)

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2086272929.py:21: DtypeWarning: Columns (137,140,167,182,183,184,185,186,187,188,189,190,191,192,193,196,197,198,199,200,201,264,325,338,339,340,341,342,343,344,345,346,347) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

First 5 rows of the original dataframe:

,hhid,hvidx,hv000,hv001,hv002,hv003,hv004,hv005,hv006,hv007,...,shb118d,shb118e,shb118f,shb118g,shb118h,shb121,shb125,shml16a,shb108t,shb110t
0,1002,1,KE6,1,2,1,1,6021054,7,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1006,1,KE6,1,6,1,1,6021054,7,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009,1,KE6,1,9,1,1,6021054,7,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1013,1,KE6,1,13,1,1,6021054,7,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1013,2,KE6,1,13,1,1,6021054,7,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All columns in the CSV file:
['hhid', 'hvidx', 'hv000', 'hv001', 'hv002', 'hv003', 'hv004', 'hv005', 'hv006', 'hv007', 'hv008', 'hv009', 'hv010', 'hv011', 'hv012', 'hv013', 'hv014', 'hv015', 'hv016', 'hv017', 'hv018', 'hv019', 'hv020', 'hv021', 'hv022', 'hv023', 'hv024', 'hv025', 'hv026', 'hv027', 'hv028', 'hv030', 'hv031', 'hv032', 'hv035', 'hv040', 'hv041', 'hv042', 'hv044', 'hv201', 'hv202', 'hv204', 'hv205', 'hv206', 'hv207', 'hv208', 'hv209', 'hv210', 'hv211', 'hv212', 'hv213', 'hv214', 'hv215', 'hv216', 'hv217', 'hv218', 'hv219', 'hv220', 'hv221', 'hv225', 'hv226', 'hv227', 'hv228', 'hv230a', 'hv230b', 'hv232', 'hv232b', 'hv232c', 'hv232d', 'hv232e', 'hv232y', 'hv234', 'hv234a', 'hv235', 'hv236', 'hv237', 'hv237a', 'hv237b', 'hv237c', 'hv237d', 'hv237e', 'hv237f', 'hv237g', 'hv237h', 'hv237i', 'hv237j', 'hv237k', 'hv237x', 'hv237z', 'hv238', 'hv239', 'hv240', 'hv241', 'hv242', 'hv243a', 'hv243b', 'hv243c', 'hv243d', 'hv244', 'hv245', 'hv246', 'hv246a', 'hv246b', 'hv246c', 'hv246d', 'hv246e', 'hv246f', 'hv246g', 'hv246h', 'hv246i', 'hv246j', 'hv246k', 'hv247', 'hv252', 'hv253', 'hv253a', 'hv253b', 'hv253c', 'hv253d', 'hv253e', 'hv253f', 'hv253g', 'hv253h', 'hv253x', 'hv253z', 'hv270', 'hv271', 'hml1', 'hml1a', 'hml2', 'shcounty', 'shzone', 'shbegin', 'shend', 'shlang', 'shlangint', 'shtransl', 'sh101a', 'sh109b', 'sh111u', 'sh111', 'sh112e', 'sh112g', 'sh112h', 'sh112i', 'sh112j', 'sh112k', 'sh112l', 'sh112m', 'sh112n', 'sh112o', 'sh112p', 'sh113aa', 'sh113bb', 'sh113cc', 'sh128a', 'sh128b', 'sh128c', 'sh128d', 'sh128e1', 'sh128e2', 'sh128e3', 'sh128e4', 'sh128e5', 'sh128e6', 'sh128e7', 'sh128e8', 'sh128f', 'sh128g1', 'sh128g2', 'sh128g3', 'sh128g4', 'sh128g5', 'sh128g6', 'sh128g7', 'sh128g8', 'sh128g9', 'sh128g10', 'sh128h1', 'sh128h2', 'sh128h3', 'sh128h4', 'sh128i', 'sh128j', 'sh128k', 'sh128l', 'sh128m', 'sh128n', 'sh128o', 'sh128p', 'sh128q', 'sh128r', 'sh128s', 'sh128t', 'sh128u', 'sh128v', 'sh128x1', 'sh128x2', 'sh128x3', 'sh128x4', 'sh128x5', 'sh128y', 'sh128z', 'sh129a', 'sh129b', 'sh129c', 'sh129d', 'sh129e', 'sh129f', 'sh129g', 'sh129h', 'hv101', 'hv102', 'hv103', 'hv104', 'hv105', 'hv106', 'hv107', 'hv108', 'hv109', 'hv110', 'hv111', 'hv112', 'hv113', 'hv114', 'hv115', 'hv116', 'hv117', 'hv118', 'hv120', 'hv121', 'hv122', 'hv123', 'hv124', 'hv125', 'hv126', 'hv127', 'hv128', 'hv129', 'hv140', 'hc0', 'hc1', 'hc2', 'hc3', 'hc4', 'hc5', 'hc6', 'hc7', 'hc8', 'hc9', 'hc10', 'hc11', 'hc12', 'hc13', 'hc15', 'hc16', 'hc17', 'hc18', 'hc19', 'hc27', 'hc30', 'hc31', 'hc32', 'hc33', 'hc51', 'hc52', 'hc53', 'hc55', 'hc56', 'hc57', 'hc58', 'hc60', 'hc61', 'hc62', 'hc63', 'hc64', 'hc68', 'hc70', 'hc71', 'hc72', 'hc73', 'shc1', 'hmlidx', 'hml3', 'hml4', 'hml5', 'hml6', 'hml7', 'hml8', 'hml9', 'hml10', 'hml11', 'hml21', 'hmla', 'hmlb', 'hmlc', 'hmld', 'hmle', 'sh121a', 'sh125', 'sh125a', 'sh126a1', 'sh126a2', 'sh126a3', 'sh126a4', 'sh126a5', 'sh126a6', 'sh126a7', 'sh127bb', 'sh127cc1', 'sh127cc2', 'sh127cc3', 'sh127cc4', 'sh127cc5', 'hmhidx', 'hml12', 'hml13', 'hml14', 'hml15', 'hml16', 'hml16a', 'hml17', 'hml18', 'hml19', 'hml20', 'hml30', 'hml31', 'hml32', 'hml32a', 'hml32b', 'hml32c', 'hml32d', 'hml32e', 'hml32f', 'hml32g', 'hml33', 'hml34', 'hml35', 'shb118a', 'shb118b', 'shb118c', 'shb118d', 'shb118e', 'shb118f', 'shb118g', 'shb118h', 'shb121', 'shb125', 'shml16a', 'shb108t', 'shb110t']

Renamed the following columns:
  hml12 -> net_owned
  hml20 -> net_used
  hv001 -> cluster
  hv024 -> region
  hv021 -> stratum
  hv025 -> residence

Warning: Could not rename the following columns (not found in selection):
  hml12 -> net_owned
  hml20 -> net_used
  hv001 -> cluster
  hv024 -> region
  hv021 -> stratum
  hv025 -> residence

First 5 rows of the extracted dataframe:

                   net_owned net_used  cluster   region  stratum residence
0    only treated (itn) nets      yes        1  nairobi        1     urban
1  did not sleep under a net       no        1  nairobi        1     urban
2    only treated (itn) nets      yes        1  nairobi        1     urban
3    only treated (itn) nets      yes        1  nairobi        1     urban
4    only treated (itn) nets      yes        1  nairobi        1     urban

Successfully extracted 6 columns to exports/household_member-extr_2015.csv

In [5]:
# Configuration cells - modify these values
input_file = "data/household_member-2020.csv"  # Replace with your actual input file path
output_file = "exports/household_member-extr_2020.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "hml12",
    "shcounty",	
    "hv001",	
    "hv024",	
    "hv021",	
    "hv025",
]

column_rename_dict = {
    "hml12": "net_owned",   # Number of ITNs in the household
    "shcounty": "county",   # County name (custom DHS variable)
    "hv001": "cluster",     # Cluster number
    "hv024": "region",      # Region/province
    "hv021": "stratum",     # Sampling stratum
    "hv025": "residence"    # Urban/rural residence
}





# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_rename_dict)

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2086272929.py:21: DtypeWarning: Columns (53,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

First 5 rows of the original dataframe:

,hhid,hvidx,hv000,hv001,hv002,hv003,hv004,hv005,hv006,hv007,...,hml32c,hml32d,hml32e,hml32f,hml32g,hml33,hml34,hml35,hml36,sml16a
0,2 1,1,KE7,2,1,8,2,588318,11,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2 1,2,KE7,2,1,8,2,588318,11,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2 1,3,KE7,2,1,8,2,588318,11,2020,...,no,no,NaN,NaN,NaN,measured,C5B7P,negative,305.0,138.0
3,2 1,4,KE7,2,1,8,2,588318,11,2020,...,no,no,NaN,NaN,NaN,measured,P6G7J,negative,305.0,114.0
4,2 1,5,KE7,2,1,8,2,588318,11,2020,...,no,no,NaN,NaN,NaN,measured,B0V4B,negative,305.0,80.0

All columns in the CSV file:
['hhid', 'hvidx', 'hv000', 'hv001', 'hv002', 'hv003', 'hv004', 'hv005', 'hv006', 'hv007', 'hv008', 'hv008a', 'hv009', 'hv010', 'hv011', 'hv012', 'hv013', 'hv014', 'hv015', 'hv016', 'hv017', 'hv018', 'hv019', 'hv020', 'hv021', 'hv022', 'hv023', 'hv024', 'hv025', 'hv026', 'hv027', 'hv028', 'hv030', 'hv031', 'hv032', 'hv035', 'hv040', 'hv041', 'hv042', 'hv045a', 'hv045b', 'hv045c', 'hv046', 'hv801', 'hv802', 'hv803', 'hv804', 'hv807d', 'hv807m', 'hv807y', 'hv807c', 'hv807a', 'hv201', 'hv202', 'hv201a', 'hv204', 'hv205', 'hv206', 'hv207', 'hv208', 'hv209', 'hv210', 'hv211', 'hv212', 'hv213', 'hv214', 'hv215', 'hv216', 'hv217', 'hv218', 'hv219', 'hv220', 'hv221', 'hv225', 'hv226', 'hv227', 'hv228', 'hv235', 'hv238', 'hv238a', 'hv239', 'hv240', 'hv241', 'hv242', 'hv243a', 'hv243b', 'hv243c', 'hv243d', 'hv243e', 'hv244', 'hv245', 'hv246', 'hv246a', 'hv246b', 'hv246c', 'hv246d', 'hv246e', 'hv246f', 'hv246g', 'hv246h', 'hv246i', 'hv246j', 'hv246k', 'hv247', 'hv270', 'hv271', 'hv270a', 'hv271a', 'hml1', 'hml1a', 'hml2', 'shcounty', 'shzone', 'sh109', 'sh110', 'sh116g', 'sh116h', 'sh116i', 'sh116j', 'sh116k', 'sh116l', 'sh116m', 'sh116n', 'sh116o', 'sh116p', 'sh119', 'sh119a', 'hv101', 'hv102', 'hv103', 'hv104', 'hv105', 'hv117', 'hv120', 'hc0', 'hc1', 'hc1a', 'hc16', 'hc17', 'hc18', 'hc19', 'hc20', 'hc21', 'hc27', 'hc30', 'hc31', 'hc32', 'hc32a', 'hc33', 'hc51', 'hc52', 'hc53', 'hc55', 'hc56', 'hc57', 'hc58', 'hc60', 'hc61', 'hc62', 'hc63', 'hc64', 'hc68', 'shc1', 'shc1a', 'sb115a', 'sb115b', 'sb115c', 'sb115d', 'sb115e', 'sb115f', 'sb115g', 'sb115h', 'sb119', 'sb122', 'sb123', 'sb128d', 'sb128m', 'sb128y', 'hmlidx', 'hml3', 'hml4', 'hml5', 'hml6', 'hml7', 'hml8', 'hml9', 'hml10', 'hml11', 'hml21', 'hmla', 'hmlb', 'hmlc', 'hmld', 'hmle', 'hml22', 'hml23', 'sh130', 'hmhidx', 'hml12', 'hml13', 'hml14', 'hml15', 'hml16', 'hml16a', 'hml17', 'hml18', 'hml19', 'hml20', 'hml30', 'hml31', 'hml32', 'hml32a', 'hml32b', 'hml32c', 'hml32d', 'hml32e', 'hml32f', 'hml32g', 'hml33', 'hml34', 'hml35', 'hml36', 'sml16a']

Renamed the following columns:
  hml12 -> net_owned
  shcounty -> county
  hv001 -> cluster
  hv024 -> region
  hv021 -> stratum
  hv025 -> residence

Warning: Could not rename the following columns (not found in selection):
  hml12 -> net_owned
  shcounty -> county
  hv001 -> cluster
  hv024 -> region
  hv021 -> stratum
  hv025 -> residence

First 5 rows of the extracted dataframe:

                 net_owned county  cluster region  stratum residence
0  only treated (itn) nets  kwale        2  coast        2     rural
1  only treated (itn) nets  kwale        2  coast        2     rural
2  only treated (itn) nets  kwale        2  coast        2     rural
3  only treated (itn) nets  kwale        2  coast        2     rural
4  only treated (itn) nets  kwale        2  coast        2     rural

Successfully extracted 6 columns to exports/household_member-extr_2020.csv

In [6]:
# Configuration cells - modify these values
input_file = "data/household_2020.csv"  # Replace with your actual input file path
output_file = "exports/household_extr_2020.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "hv001",
    "hv227",
    "hv012",	
    "hmlidx_1",	
    "hmlidx_2",	
    "hmlidx_3",	
    "hmlidx_4",
    "hmlidx_5",
    "hmlidx_6",
    "hmlidx_7"
]

column_rename_dict = {
    "hv001": "cluster",     # Cluster number
    "hv227": "net_use",     # Slept under an ITN last night
    "hv012": "hh_size",     # Household size
    "hmlidx_1": "net_idx1", # ITN index 1 (person)
    "hmlidx_2": "net_idx2", # ITN index 2 (person)
    "hmlidx_3": "net_idx3", # ITN index 3 (person)
    "hmlidx_4": "net_idx4", # ITN index 4 (person)
    "hmlidx_5": "net_idx5", # ITN index 5 (person)
    "hmlidx_6": "net_idx6", # ITN index 6 (person)
    "hmlidx_7": "net_idx7"  # ITN index 7 (person)
}


# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_rename_dict)

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2086272929.py:21: DtypeWarning: Columns (52,70,89,162,163,164,165,166,167,168,169,170,171,172,173,186,187,188,189,190,191,192,193,194,195,196,197,210,211,212,213,214,215,216,217,218,219,220,221,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,266,267,268,282,283,284,285,286,287,288,289,290,291,292,293,306,307,308,309,310,311,312,313,314,315,316,317,344,345,346,347,348,350,351,352,364,365,366,367,368,370,505,506,507,508,509,510,511,512,605,606,607,608,609,610,611,612,618,619,620,621,622,623,624,625,626,645,646,647,648,649,650,651,652,661,662,663,664,665,667,685,686,687,688,689,690,691,692,725,726,727,728,729,730,731,732,764,765,766,767,768,769,770,771,772,785,786,787,788,789,790,865,866,867,868,869,870,920,922,923,924,925,926,927,928,940,942,943,944,945,946,947,948,960,962,963,964,965,966,967,968,980,982,983,984,985,986,987,988,1000,1002,1003,1004,1005,1006,1007,1008,1020,1022,1023,1024,1025,1026,1027,1028,1040,1042,1043,1044,1045,1046,1047,1048,1060,1062,1063,1064,1065,1066,1067,1068,1080,1082,1083,1084,1085,1086,1087,1088,1098,1100,1102,1103,1104,1105,1106,1107,1108,1165,1166,1167,1168,1169,1170,1171,1172,1217,1218,1321,1322,1323,1329,1330,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1451,1452,1453,1454,1455,1456,1457,1460,1461,1463,1471,1472,1473,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1530,1531,1532,1533,1534,1535,1536,1537,1539,1541,1543,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1612,1631,1632,1633,1634,1635,1636,1637,1638,1639,1642,1655,1656,1657,1658,1659,1660,1661,1662,1679,1680,1681,1682,1683,1684,1685,1686,1687,1690,1703,1704,1705,1706,1707,1708,1709,1710,1711,1714,1727,1728,1729,1730,1731,1732,1733,1734,1735,1738,1751,1752,1753,1754,1755,1756,1757,1758,1759,1762,1847,1848,1849,1850,1851,1852,1853,1854,1855,1858,1871,1872,1873,1874,1875,1876,1877,1878,1895,1896,1897,1898,1899,1900,1901,1902) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

First 5 rows of the original dataframe:

,hhid,hv000,hv001,hv002,hv003,hv004,hv005,hv006,hv007,hv008,...,sml16a_15,sml16a_16,sml16a_17,sml16a_18,sml16a_19,sml16a_20,sml16a_21,sml16a_22,sml16a_23,sml16a_24
0,2 1,KE7,2,1,8,2,588318,11,2020,1451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2 6,KE7,2,6,2,2,588318,11,2020,1451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2 10,KE7,2,10,2,2,588318,11,2020,1451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2 13,KE7,2,13,1,2,588318,11,2020,1451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2 16,KE7,2,16,3,2,588318,11,2020,1451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All columns in the CSV file:

,cluster,net_use,hh_size,net_idx1,net_idx2,net_idx3,net_idx4,net_idx5,net_idx6,net_idx7
0,2,yes,8,1.0,2.0,3.0,4.0,NaN,NaN,NaN
1,2,no,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,yes,6,1.0,2.0,3.0,NaN,NaN,NaN,NaN
3,2,yes,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2,yes,4,1.0,NaN,NaN,NaN,NaN,NaN,NaN

Successfully extracted 10 columns to exports/household_extr_2020.csv

In [7]:
# Configuration cells - modify these values
input_file = "data/household_2015.csv"  # Replace with your actual input file path
output_file = "exports/household_extr_2015.csv"  # Replace with your desired output file path
	
# Replace with your identified column names
columns_to_keep = [
    "hv001",
    "hv227",
    "hv012",	
    "hmlidx_1",	
    "hmlidx_2",	
    "hmlidx_3",	
    "hmlidx_4",
    "hmlidx_5",
    "hmlidx_6",
    "hmlidx_7"
]

column_rename_dict = {
    "hv001": "cluster",     # Cluster number
    "hv227": "net_use",     # Whether household member slept under ITN last night
    "hv012": "hh_size",     # Total number of usual household members
    "hmlidx_1": "netidx_1", # ITN usage index 1
    "hmlidx_2": "netidx_2", # ITN usage index 2
    "hmlidx_3": "netidx_3", # ITN usage index 3
    "hmlidx_4": "netidx_4", # ITN usage index 4
    "hmlidx_5": "netidx_5", # ITN usage index 5
    "hmlidx_6": "netidx_6", # ITN usage index 6
    "hmlidx_7": "netidx_7"  # ITN usage index 7
}


# Execute the function in Jupyter
if not os.path.exists(input_file):
    print(f"Error: Input file '{input_file}' not found.")
else:
    result_df = extract_columns(input_file, output_file, columns_to_keep, column_rename_dict)

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2086272929.py:21: DtypeWarning: Columns (56,88,98,136,139,166,181,182,183,184,185,186,187,188,189,190,191,192,195,196,197,198,199,200,238,239,240,241,242,243,244,245,246,247,248,249,258,259,260,261,262,263,264,265,266,267,268,269,278,279,280,281,282,283,284,285,286,287,288,289,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,558,559,560,561,562,563,564,565,566,567,568,569,598,599,600,601,602,603,604,605,606,607,608,609,828,829,830,831,832,833,834,835,836,1020,1021,1022,1023,1024,1025,1026,1027,1028,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1177,1178,1179,1180,1181,1182,1185,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1248,1249,1250,1251,1252,1253,1254,1255,1256,1262,1263,1264,1265,1266,1267,1271,1318,1319,1320,1321,1322,1323,1327,1409,1410,1411,1416,1417,1418,1430,1431,1432,1437,1438,1439,1444,1445,1446,1458,1459,1460,1472,1473,1474,1514,1515,1516,1521,1522,1523,1528,1529,1530,1535,1536,1537,1542,1543,1544,1549,1550,1551,1556,1557,1558,1563,1564,1565,1570,1571,1572,1577,1578,1579,1584,1585,1586,1590,1591,1592,1593,1597,1598,1599,1600,1604,1605,1606,1607,1611,1612,1613,1614,1618,1619,1620,1621,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1722,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1788,1789,1790,1791,1792,1794,1795,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1843,1844,1845,1846,1847,1848,1849,1850,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

First 5 rows of the original dataframe:

,hhid,hv000,hv001,hv002,hv003,hv004,hv005,hv006,hv007,hv008,...,shb110t_11,shb110t_12,shb110t_13,shb110t_14,shb110t_15,shb110t_16,shb110t_17,shb110t_18,shb110t_19,shb110t_20
0,1002,KE6,1,2,1,1,6021054,7,2015,1387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1006,KE6,1,6,1,1,6021054,7,2015,1387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009,KE6,1,9,1,1,6021054,7,2015,1387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1013,KE6,1,13,1,1,6021054,7,2015,1387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1016,KE6,1,16,1,1,6021054,7,2015,1387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All columns in the CSV file:

,cluster,net_use,hh_size,netidx_1,netidx_2,netidx_3,netidx_4,netidx_5,netidx_6,netidx_7
0,1,yes,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,no,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,yes,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,yes,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,no,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Successfully extracted 10 columns to exports/household_extr_2015.csv

## Data Aggregation

In [8]:
import pandas as pd
import numpy as np
from typing import Dict, List, Union, Callable

def aggregate_by_cluster(
    df: pd.DataFrame,
    cluster_column: str,
    category_columns: List[str] = None,
    aggregation_methods: Dict[str, Union[str, List[str], Callable]] = None
) -> pd.DataFrame:
    """
    Aggregate a dataframe by cluster with separate count columns for categorical variables.
    
    Parameters:
    -----------
    df : pandas DataFrame
        The input dataframe to be aggregated
    cluster_column : str
        The column name containing cluster assignments
    category_columns : list, optional
        List of categorical columns to create separate count columns for each unique value
    aggregation_methods : dict, optional
        Dictionary mapping column names to aggregation methods
        If a column is not specified, default aggregations will be applied
    
    Returns:
    --------
    pandas DataFrame
        Aggregated dataframe with one row per cluster and separate count columns for categories
    """
    if aggregation_methods is None:
        aggregation_methods = {}
    
    if category_columns is None:
        category_columns = []
    
    # Make a copy of the dataframe to avoid modifying the original
    data = df.copy()
    
    # Create result dataframe starting with cluster counts
    result = pd.DataFrame(data[cluster_column].value_counts().sort_index())
    result.columns = ['total_count']
    
    # Process each categorical column to create separate count columns
    for col in category_columns:
        if col in data.columns and col != cluster_column:
            # Get unique values in this column
            unique_values = data[col].dropna().unique()
            
            # For each unique value, create a count column
            for val in unique_values:
                # Create a new column with count of this value in each cluster
                count_series = data[data[col] == val].groupby(cluster_column).size()
                result[f"{col}_{val}"] = count_series
    
    # Handle the remaining columns with the standard aggregation function
    # Remove category columns from aggregation_methods
    remaining_agg_methods = {k: v for k, v in aggregation_methods.items() 
                            if k not in category_columns and k != cluster_column}
    
    # Identify remaining columns
    remaining_cols = [col for col in data.columns 
                     if col not in category_columns and col != cluster_column]
    
    if remaining_cols:
        # Create a subset dataframe with only the remaining columns
        subset_df = data[[cluster_column] + remaining_cols].copy()
        
        # Apply standard aggregation to remaining columns
        standard_aggs = {}
        
        # Identify numeric and categorical columns
        numeric_cols = subset_df.select_dtypes(include=['number']).columns.tolist()
        cat_cols = subset_df.select_dtypes(include=['object', 'category']).columns.tolist()
        
        if cluster_column in numeric_cols:
            numeric_cols.remove(cluster_column)
        if cluster_column in cat_cols:
            cat_cols.remove(cluster_column)
        
        # Apply user-specified aggregation methods
        for col, agg_method in remaining_agg_methods.items():
            if col in subset_df.columns:
                standard_aggs[col] = agg_method
        
        # Apply default aggregations for numeric columns not specified
        for col in numeric_cols:
            if col not in standard_aggs:
                standard_aggs[col] = ['mean', 'median', 'min', 'max']
        
        # Apply default aggregations for remaining categorical columns
        for col in cat_cols:
            if col not in standard_aggs:
                standard_aggs[col] = [
                    ('mode', lambda x: x.mode()[0] if not x.mode().empty else np.nan),
                    ('unique_count', 'nunique')
                ]
        
        if standard_aggs:
            # Perform standard aggregation
            standard_result = subset_df.groupby(cluster_column).agg(standard_aggs)
            
            # Flatten the column names if multi-level
            if isinstance(standard_result.columns, pd.MultiIndex):
                standard_result.columns = [f"{col[0]}_{col[1]}" if isinstance(col, tuple) else col 
                                         for col in standard_result.columns]
            
            # Join with the result dataframe
            result = result.join(standard_result)
    
    # Fill NaN values with 0 for count columns
    count_cols = [col for col in result.columns if col != 'total_count' and not col.startswith(('age_', 'stratum_', 'region_'))]
    result[count_cols] = result[count_cols].fillna(0).astype(int)
    
    return result

In [9]:
def aggregate_dataset(
    df, 
    cluster_column='cluster',
    category_columns=None,
    numeric_columns=None,
    simple_agg_columns=None,
    custom_agg_methods=None,
    file_format='csv',
    **kwargs
):
    """
    Reads a dataset file and performs cluster-based aggregation with customizable settings.
    
    Parameters:
    -----------
    file_path : str
        Path to the data file
    cluster_column : str, default='cluster'
        The column name containing cluster assignments
    category_columns : list or None, default=None
        List of categorical columns to create separate count columns for each unique value
    numeric_columns : list or None, default=None
        List of numeric columns to apply numeric aggregations to
    simple_agg_columns : dict or None, default=None
        Dictionary mapping column names to simple aggregation method (e.g., {'region': 'first'})
    custom_agg_methods : dict or None, default=None
        Dictionary mapping column names to custom aggregation methods
    file_format : str, default='csv'
        Format of input file ('csv', 'excel', etc.)
    **kwargs : 
        Additional arguments to pass to the file reading function (e.g., sep=',', encoding='utf-8')
    
    Returns:
    --------
    pandas DataFrame
        Aggregated dataframe with one row per cluster
    """
    import pandas as pd
    import numpy as np
    
    # Set defaults for optional parameters
    if category_columns is None:
        category_columns = []
    if numeric_columns is None:
        numeric_columns = []
    if simple_agg_columns is None:
        simple_agg_columns = {}
    if custom_agg_methods is None:
        custom_agg_methods = {}
    
    # Convert numeric columns if specified
    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # Prepare aggregation methods
    agg_methods = {}
    
    # Add simple aggregations (like 'first', 'last', etc.)
    for col, method in simple_agg_columns.items():
        if col in df.columns and col != cluster_column:
            agg_methods[col] = method
    
    # Add custom aggregation methods
    for col, method in custom_agg_methods.items():
        if col in df.columns and col != cluster_column:
            agg_methods[col] = method
    
    # Perform the aggregation
    result = aggregate_by_cluster(df, cluster_column, category_columns, agg_methods)
    return result

In [10]:
result = aggregate_dataset(
        pd.read_csv('exports/children_extr_2015.csv'),
        cluster_column='cluster',
        category_columns=['treat_src', 'residence', 'alive', 'fever_rec'],
        numeric_columns=['age_mo'],
        simple_agg_columns={
            'stratum': 'first',
            'region': 'first'
        },
        custom_agg_methods={
            'age_mo': ['mean', 'min', 'max', 'count']
        }
    )

result_foc = [
    'total_count',
    'treat_src_yes',
    'residence_urban',
    'residence_rural',
    'alive_yes',
    'fever_rec_only treated nets'
]

children_2015 = result[result_foc].reset_index()

In [11]:
result = aggregate_dataset(
        pd.read_csv('exports/children_extr_2020.csv'),
        cluster_column='cluster',
        category_columns=['treat_src', 'residence', 'alive', 'fever_rec'],
        numeric_columns=['age_mo'],
        simple_agg_columns={
            'stratum': 'first',
            'region': 'first'
        },
        custom_agg_methods={
            'age_mo': ['mean', 'min', 'max', 'count']
        }
    )

result_foc = [
    'total_count',
    'treat_src_yes',
    'residence_urban',
    'residence_rural',
    'alive_yes',
    'fever_rec_only treated nets'
]

children_2020 = result[result_foc].reset_index()

In [12]:
df = pd.read_csv('exports/household_extr_2015.csv')
col_max = df.loc[:,'netidx_1':'netidx_7'].columns.to_list()
df['nets'] = df[col_max].max(axis=1).fillna(0)
df = df.drop(df.loc[:,'netidx_1':'netidx_7'].columns.to_list(), axis=1)

result = aggregate_dataset(
        df,
        cluster_column='cluster',
        category_columns=['net_use'],
        numeric_columns=['nets','hh_size'],
        # simple_agg_columns={},
        custom_agg_methods={
            'nets': ['mean', 'min', 'max', 'count', 'sum'],
            'hh_size': ['mean', 'min', 'max', 'count', 'sum']
        }
    )
household_2015 = result[
    [
        'total_count', 
        'net_use_yes',
        'nets_sum',
        'hh_size_mean',
        'hh_size_sum'
    ]
].reset_index()
# household_2015

In [13]:
df = pd.read_csv('exports/household_extr_2020.csv')
col_max = df.loc[:,'net_idx1':'net_idx7'].columns.to_list()
df['nets'] = df[col_max].max(axis=1).fillna(0)
df = df.drop(df.loc[:,'net_idx1':'net_idx7'].columns.to_list(), axis=1)

result = aggregate_dataset(
        df,
        cluster_column='cluster',
        category_columns=['net_use'],
        numeric_columns=['nets','hh_size'],
        # simple_agg_columns={},
        custom_agg_methods={
            'nets': ['mean', 'min', 'max', 'count', 'sum'],
            'hh_size': ['mean', 'min', 'max', 'count', 'sum']
        }
    )
household_2020 = result[
    [
        'total_count', 
        'net_use_yes',
        'nets_sum',
        'hh_size_mean',
        'hh_size_sum'
    ]
].reset_index()

In [14]:
df = pd.read_csv('exports/household_member-extr_2015.csv')

result = aggregate_dataset(
        df,
        cluster_column='cluster',
        category_columns=['residence', 'net_used','net_owned']
    )
result
household_member_2015 = result[
    [
        'total_count', 
        'residence_urban',
        'net_used_yes',
        'region_mode',
        'net_owned_only treated (itn) nets',
        'net_owned_did not sleep under a net'
    ]
].reset_index()
# household_member_2015

In [15]:
df = pd.read_csv('exports/household_member-extr_2020.csv')

result = aggregate_dataset(
        df.drop(['county'], axis=1),
        cluster_column='cluster',
        category_columns=['residence','net_owned'],
        
    )
result
household_member_2020 = result[
    ['total_count', 'residence_urban','region_mode','net_owned_only treated (itn) nets','net_owned_did not sleep under a net']
].reset_index()
# household_member_2020

## Data Joining

### 2015 data 
The 2015 data is joined to the spatial points of data collection according to cluster, then to the spatial covariates according to the cluster as well.

In [16]:
# Importing the shapefile for 2015
import geopandas as gpd

path_to_shp = './data/shp/_2015/KEGE7AFL.shp'
dhs15_points_shp = gpd.read_file(path_to_shp)
dhs15_points_shp.columns
dhs15_points_shp = dhs15_points_shp.drop(dhs15_points_shp.loc[:,'CCFIPS':'SOURCE'].columns.to_list(), axis=1)

In [17]:
dhs15_points_shp 
meg_15_ch = pd.merge(dhs15_points_shp, children_2015, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_sh','_ch'))
meg_15_ch_hh = pd.merge(meg_15_ch, household_2015, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_shch','_hh'))
meg_15_ch_hh_hhm = pd.merge(meg_15_ch_hh, household_member_2015, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_shchhh','_hhm'))
meg_15_ch_hh_hhm.to_csv('meg15.csv')

In [18]:
def isolate_columns(columns, year_suffix="_15"):
    """
    Isolates columns ending with the specified suffix and constant columns without numerical suffixes,
    excluding temperature columns from constants
    
    Args:
        columns (list): List of column names
        year_suffix (str): Suffix to filter for (default: "_15")
        
    Returns:
        tuple: (columns_with_suffix, constant_columns, combined_columns)
    """
    import re
    
    # Find columns ending with the specified suffix
    # Handle both formats like "_15" and just "15"
    columns_with_suffix = [col for col in columns if col.endswith(year_suffix) or 
                          (year_suffix.startswith('_') and col.endswith(year_suffix[1:]))]
    
    # Find constant columns without numerical suffix
    # Pattern to match columns ending with numbers
    pattern = re.compile(r'\d+$')
    
    # Columns that don't end with numbers
    constant_columns = [col for col in columns if not pattern.search(col)]
    
    # Remove temperature columns from the constant columns
    constant_columns = [col for col in constant_columns 
                        if not col.startswith('Temperature_')]
    
    # Combined list of both types
    combined_columns = columns_with_suffix + constant_columns
    
    return columns_with_suffix, constant_columns, combined_columns

In [19]:
path_to_cov = './data/geospatial_covariates_2015.csv'
df = pd.read_csv(path_to_cov)
x,y,select_cols = isolate_columns(df.columns.to_list())
cov_15 = df[select_cols]

In [20]:
mal_2015 = pd.merge(meg_15_ch_hh_hhm, cov_15, 'inner',on=['DHSCLUST','DHSID'], suffixes=('_hhm','_cov'))
mal_2015.to_csv('malaria_15.csv')
gpd.GeoDataFrame(mal_2015,geometry='geometry').to_file('shp/malaria_15.shp', driver='ESRI Shapefile')

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\2880136839.py:3: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gpd.GeoDataFrame(mal_2015,geometry='geometry').to_file('shp/malaria_15.shp', driver='ESRI Shapefile')
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_hhm' to 'DHSYEAR_hh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'cluster_shch' to 'cluster_sh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_shch' to 'total_coun'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'treat_src_yes' to 'treat_src_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_urban_shchhh' to 'residence_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_rural' to 'residenc_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'fever_rec_only treated nets' to 'fever_rec_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_hh' to 'total_co_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_use_yes' to 'net_use_ye'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_mean' to 'hh_size_me'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_sum' to 'hh_size_su'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count' to 'total_co_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_urban_hhm' to 'residenc_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_used_yes' to 'net_used_y'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'region_mode' to 'region_mod'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_only treated (itn) nets' to 'net_owned_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_did not sleep under a net' to 'net_owne_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Travel_Times_2015' to 'Travel_Tim'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'GPS_Dataset' to 'GPS_Datase'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_cov' to 'DHSYEAR_co'
  ogr_write(

### 2020 data
The 2020 data is joined to the spatial points of data collection according to cluster, then to the spatial covariates according to the cluster as well.

In [21]:
path_to_shp = './data/shp/_2020/KEGE81FL.shp'
dhs20_points_shp = gpd.read_file(path_to_shp)
dhs20_points_shp.columns
dhs20_points_shp = dhs20_points_shp.drop(dhs20_points_shp.loc[:,'CCFIPS':'SOURCE'].columns.to_list(), axis=1)

In [22]:
dhs20_points_shp 
meg_20_ch = pd.merge(dhs20_points_shp, children_2020, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_sh','_ch'))
meg_20_ch_hh = pd.merge(meg_20_ch, household_2020, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_shch','_hh'))
meg_20_ch_hh_hhm = pd.merge(meg_20_ch_hh, household_member_2020, how='inner', right_on='cluster', left_on='DHSCLUST', suffixes=('_shchhh','_hhm'))
meg_20_ch_hh_hhm.to_csv('meg20.csv')

In [23]:
path_to_cov = './data/geospatial_covariates_2020.csv'
df = pd.read_csv(path_to_cov)
x,y,select_cols = isolate_columns(df.columns.to_list(), '_20')
cov_20 = df[select_cols]
select_cols

['pop2020',
 'arid_20',
 'DLST_20',
 'DTemp20',
 'EVI20',
 'FD_20',
 'ITN_20',
 'LST_20',
 'MI_20',
 'MP_20',
 'Matemp20',
 'Meantem20',
 'Mintem20',
 'NLST20',
 'PET_20',
 'Prec20',
 'Rain20',
 'U5pop20',
 'UNpopc20',
 'UNpop20',
 'WD_20',
 'DHSID',
 'GPS_Dataset',
 'DHSCC',
 'DHSYEAR',
 'DHSCLUST',
 'SurveyID',
 'D.e',
 'Elev',
 'Global_Human_Footprint',
 'Growing_Season_Length',
 'Irrigation',
 'Livestock_Cattle',
 'Livestock_Chickens',
 'Livestock_Goats',
 'Livestock_Pigs',
 'Livestock_Sheep',
 'Nightligh']

In [24]:
mal_2020 = pd.merge(meg_20_ch_hh_hhm, cov_20, 'inner',on=['DHSCLUST','DHSID'], suffixes=('_hhm','_cov'))
mal_2020.to_csv('malaria_20.csv')
mal_20_gdf = gpd.GeoDataFrame(mal_2020,geometry='geometry')
mal_20_gdf.to_file('shp/malaria_20.shp', driver='ESRI Shapefile')

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\1971534842.py:4: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  mal_20_gdf.to_file('shp/malaria_20.shp', driver='ESRI Shapefile')
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_hhm' to 'DHSYEAR_hh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'cluster_shch' to 'cluster_sh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_shch' to 'total_coun'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'treat_src_yes' to 'treat_src_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_urban_shchhh' to 'residence_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_rural' to 'residenc_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'fever_rec_only treated nets' to 'fever_rec_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_hh' to 'total_co_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_use_yes' to 'net_use_ye'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_mean' to 'hh_size_me'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_sum' to 'hh_size_su'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count' to 'total_co_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'residence_urban_hhm' to 'residenc_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'region_mode' to 'region_mod'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_only treated (itn) nets' to 'net_owned_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_did not sleep under a net' to 'net_owne_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'GPS_Dataset' to 'GPS_Datase'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_cov' to 'DHSYEAR_co'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Global_Human_Footprint' to 'Global_Hum'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Growing_Season_Length' to 'Growing_Se'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Livestock_Cattle' to 'Livestock_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Livestock_Chickens' to 'Livestoc_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Livestock_Goats' to 'Livestoc_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Livestock_Pigs' to 'Livestoc_3'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Livestock_Sheep' to 'Livestoc_4'
  ogr_write(

In [25]:
gdf = gpd.read_file('shp/malaria_20.shp')

In [26]:
import pandas as pd

def rename_duplicate_columns(df):
    # Define mapping for affected columns - all names limited to 10 characters
    rename_map = {
        # Total count columns
        'total_coun': 'tot_cnt1',
        'total_co_1': 'tot_cnt2',
        'total_co_2': 'tot_cnt3',
        
        # Residence columns
        'residence_': 'res_type',
        'residenc_1': 'res_cat',
        'residenc_2': 'res_regn',
        
        # Cluster columns
        'cluster': 'cluster',  # keep as is
        'cluster_sh': 'clstr_sh',
        'cluster_hh': 'clstr_hh',
        
        # Net owned columns
        'net_owned_': 'net_own1',
        'net_owne_1': 'net_own2',
        
        # Livestock columns
        'Livestock_': 'lvstk',
        'Livestoc_1': 'lvstk_t1',
        'Livestoc_2': 'lvstk_t2',
        'Livestoc_3': 'lvstk_t3',
        'Livestoc_4': 'lvstk_t4',
        
        # Temperature columns
        'DTemp20': 'DTemp20',  # keep as is
        'Matemp20': 'MaxTmp20',
        'Meantem20': 'MeanTm20',
        'Mintem20': 'MinTmp20'
    }
    
    # Create a new DataFrame with renamed columns
    # Only rename columns that exist in the dataframe
    columns_to_rename = {col: rename_map[col] for col in df.columns if col in rename_map}
    
    if columns_to_rename:
        df = df.rename(columns=columns_to_rename)
        print(f"Renamed {len(columns_to_rename)} columns")
    else:
        print("No columns were renamed")
    
    return df

# Rename the columns
df_renamed = rename_duplicate_columns(gdf)

Renamed 20 columns

In [27]:
df_renamed.to_file('trial.shp')

In [28]:
# Filter out the columns based on region of nyanza and western
mal_2020 = mal_2020[mal_2020['region_mode'].isin(['nyanza', 'western'])]
mal_2015 = mal_2015[mal_2015['region_mode'].isin(['nyanza', 'western'])]

In [29]:
mal_2020.to_csv('malaria_20.csv')
mal_2015.to_csv('malaria_15.csv')

## Compute Proportions

In [30]:
selected_columns_2020 = [
    'DHSID', 'DHSYEAR_hhm', 'DHSCLUST', 'URBAN_RURA', 'LATNUM','LONGNUM', 'ALT_GPS', 'ALT_DEM',
    'total_count_shch', 'treat_src_yes', 'alive_yes', 'fever_rec_only treated nets',
    'total_count_hh', 'net_use_yes', 'nets_sum','hh_size_mean', 'hh_size_sum', 
    'total_count','net_owned_only treated (itn) nets','net_owned_did not sleep under a net',
    'pop2020','DLST_20','EVI20','ITN_20','MI_20', 'MP_20',
    'Meantem20','NLST20', 'Rain20','UNpop20','Nightligh','geometry',
]
# mal_2020.columns
# length of the list selected_columns_2020
len(selected_columns_2020)

# Select the columns from the DataFrame
mal_2020_selected = mal_2020[selected_columns_2020]
mal_2020_selected.head()

,DHSID,DHSYEAR_hhm,DHSCLUST,URBAN_RURA,LATNUM,LONGNUM,ALT_GPS,ALT_DEM,total_count_shch,treat_src_yes,...,EVI20,ITN_20,MI_20,MP_20,Meantem20,NLST20,Rain20,UNpop20,Nightligh,geometry
29,KE202000000550,2020.0,550.0,R,0.237279,34.689729,9999.0,1446.0,14,5,...,0.443491,0.531126,0.231811,0.197439,22.170834,16.795700,3127.357666,851.115234,0.038609,POINT (34.68973 0.23728)
30,KE202000000559,2020.0,559.0,R,0.803374,35.133722,9999.0,1844.0,14,2,...,0.393623,0.501821,0.145796,0.114942,18.723829,13.888544,1982.196533,543.636353,0.016968,POINT (35.13372 0.80337)
31,KE202000000569,2020.0,569.0,R,0.149380,34.821633,9999.0,1551.0,15,3,...,0.456375,0.510466,0.214990,0.186985,21.795486,16.112921,3089.197510,1093.904297,0.055452,POINT (34.82163 0.14938)
32,KE202000000580,2020.0,580.0,R,0.016099,34.592356,9999.0,1542.0,5,2,...,0.431860,0.503257,0.295371,0.298597,22.738657,16.835812,2890.859375,1776.383911,0.233422,POINT (34.59236 0.0161)
33,KE202000000619,2020.0,619.0,R,0.024857,34.548762,9999.0,1471.0,7,2,...,0.445508,0.513944,0.302329,0.308824,22.798611,16.961250,2839.777588,1173.807007,0.126189,POINT (34.54876 0.02486)

In [31]:
selected_columns_2015 = [
    'DHSID', 'DHSYEAR_hhm', 'DHSCLUST', 'URBAN_RURA', 'LATNUM','LONGNUM', 'ALT_GPS', 'ALT_DEM',
    'total_count_shch', 'treat_src_yes', 'alive_yes', 'fever_rec_only treated nets',
    'total_count_hh', 'net_use_yes', 'nets_sum','hh_size_mean', 'hh_size_sum', 
    'total_count','net_used_yes','net_owned_only treated (itn) nets','net_owned_did not sleep under a net',
    'Pop2015','DLST_15','EVI_15','ITN_15','MI_15', 'MP_15',
    'Meante15','NLST15', 'Rain15','UNpop15','Nightligh','geometry'
]
# mal_2015.columns
# length of the list selected_columns_2015
len(selected_columns_2015)

# Select the columns from the DataFrame
mal_2015_selected = mal_2015[selected_columns_2015]
mal_2015_selected.head()

,DHSID,DHSYEAR_hhm,DHSCLUST,URBAN_RURA,LATNUM,LONGNUM,ALT_GPS,ALT_DEM,total_count_shch,treat_src_yes,...,EVI_15,ITN_15,MI_15,MP_15,Meante15,NLST15,Rain15,UNpop15,Nightligh,geometry
121,KE201500000122,2015.0,122.0,R,0.097049,34.325073,9999.0,1242.0,11,4,...,3871.777778,0.600347,0.291314,0.262390,23.300001,17.958452,1920.900000,487.253066,0.057811,POINT (34.32507 0.09705)
122,KE201500000123,2015.0,123.0,R,0.094180,34.160814,9999.0,1219.0,8,4,...,3743.100000,0.597016,0.258272,0.220282,23.300001,17.246500,1830.000000,307.664234,0.005128,POINT (34.16081 0.09418)
123,KE201500000124,2015.0,124.0,R,0.027341,34.074090,9999.0,1172.0,16,14,...,3557.400000,0.592217,0.237986,0.190371,23.300001,17.513333,1526.555556,238.426156,0.004085,POINT (34.07409 0.02734)
124,KE201500000125,2015.0,125.0,R,-0.167817,34.380882,9999.0,1186.0,13,11,...,3216.142857,0.629793,0.239729,0.195317,23.416668,18.319148,1451.666667,405.735815,0.020560,POINT (34.38088 -0.16782)
125,KE201500000126,2015.0,126.0,U,0.057328,34.294138,9999.0,1322.0,12,2,...,3639.000000,0.586366,0.288961,0.259891,23.300001,17.870001,1887.000000,852.787528,0.521043,POINT (34.29414 0.05733)

In [32]:
mal_2015_selected = mal_2015_selected.copy()
# Proportion One: Proportion of children under 5 years of age who slept under an ITN the night before the survey
# Formula: Total number of Children who slept under an ITN (fever_rec_only treated nets) / Total number of children (alive_yes) in the cluster
mal_2015_selected['prop_children_5'] = mal_2015_selected['fever_rec_only treated nets'] / mal_2015_selected['alive_yes']

# Proportion Two: Proportion of households with at least one ITN
# Formula: Total number of households with at least one ITN (net_use_yes) / Total number of households (total_count_hh) in the cluster
mal_2015_selected['prop_households_ITN'] = mal_2015_selected['net_use_yes'] / mal_2015_selected['total_count_hh']

# Proportion Three: Proportion of individuals with access to an ITN in the household
# Formula: Total number of individuals with access to an ITN (nets_sum) / Total number of individuals (hh_size_sum) in the cluster
mal_2015_selected['prop_individuals_ITN'] = mal_2015_selected['nets_sum'] / mal_2015_selected['hh_size_sum']

# Proportion Four: Proportion of existing ITNs that were used the night before the survey
# Formula: Total number of individuals who slept under an ITN (net_use_yes) / Total number of existing ITNs (nets_sum) in the cluster
mal_2015_selected['prop_ITN_use'] = mal_2015_selected['net_use_yes'] / mal_2015_selected['nets_sum']

# Proportion Five: Proportion of individuals who slept under an ITN the night before the survey
# Formula: Total number of individuals who slept under an ITN (net_use_yes) / Total number of individuals (hh_size_sum) in the cluster
mal_2015_selected['prop_individuals_slept_ITN'] = mal_2015_selected['net_use_yes'] / mal_2015_selected['hh_size_sum']

# Proportion Six: Proportion of households with at least one ITN for every 2 people
# Formula: Total number of households with at least one ITN (net_use_yes) / (Total number of households (total_count_hh) * 2) in the cluster
mal_2015_selected['prop_households_ITN_2'] = mal_2015_selected['net_use_yes'] / (mal_2015_selected['total_count_hh'] * 2)

In [33]:
mal_2020_selected = mal_2020_selected.copy()
# Proportion One: Proportion of children under 5 years of age who slept under an ITN the night before the survey
# Formula: Total number of Children who slept under an ITN (fever_rec_only treated nets) / Total number of children (alive_yes) in the cluster
mal_2020_selected['prop_children_5'] = mal_2020_selected['fever_rec_only treated nets'] / mal_2020_selected['alive_yes']

# Proportion Two: Proportion of households with at least one ITN
# Formula: Total number of households with at least one ITN (net_use_yes) / Total number of households (total_count_hh) in the cluster
mal_2020_selected['prop_households_ITN'] = mal_2020_selected['net_use_yes'] / mal_2020_selected['total_count_hh']

# Proportion Three: Proportion of individuals with access to an ITN in the household
# Formula: Total number of individuals with access to an ITN (nets_sum) / Total number of individuals (hh_size_sum) in the cluster
mal_2020_selected['prop_individuals_ITN'] = mal_2020_selected['nets_sum'] / mal_2020_selected['hh_size_sum']

# Proportion Four: Proportion of existing ITNs that were used the night before the survey
# Formula: Total number of individuals who slept under an ITN (net_use_yes) / Total number of existing ITNs (nets_sum) in the cluster
mal_2020_selected['prop_ITN_use'] = mal_2020_selected['net_use_yes'] / mal_2020_selected['nets_sum']

# Proportion Five: Proportion of individuals who slept under an ITN the night before the survey
# Formula: Total number of individuals who slept under an ITN (net_use_yes) / Total number of individuals (hh_size_sum) in the cluster
mal_2020_selected['prop_individuals_slept_ITN'] = mal_2020_selected['net_use_yes'] / mal_2020_selected['hh_size_sum']

# Proportion Six: Proportion of households with at least one ITN for every 2 people
# Formula: Total number of households with at least one ITN (net_use_yes) / (Total number of households (total_count_hh) * 2) in the cluster
mal_2020_selected['prop_households_ITN_2'] = mal_2020_selected['net_use_yes'] / (mal_2020_selected['total_count_hh'] * 2)

In [42]:
mal_2015_selected = mal_2015_selected[mal_2015_selected['MP_15'] != -9999]

In [43]:
mal_2015_selected.to_csv('./data/exports/malaria_2015_selected.csv', index=False)
mal_2020_selected.to_csv('./data/exports/malaria_2020_selected.csv', index=False)

In [44]:
mal_2015_selected.to_file('shp/malaria_2015_selected.shp', driver='ESRI Shapefile')
mal_2020_selected.to_file('shp/malaria_2020_selected.shp', driver='ESRI Shapefile')

C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\46379431.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  mal_2015_selected.to_file('shp/malaria_2015_selected.shp', driver='ESRI Shapefile')
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_hhm' to 'DHSYEAR_hh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_shch' to 'total_coun'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'treat_src_yes' to 'treat_src_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'fever_rec_only treated nets' to 'fever_rec_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_hh' to 'total_co_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_use_yes' to 'net_use_ye'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_mean' to 'hh_size_me'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_sum' to 'hh_size_su'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count' to 'total_co_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_used_yes' to 'net_used_y'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_only treated (itn) nets' to 'net_owned_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_did not sleep under a net' to 'net_owne_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_children_5' to 'prop_child'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_households_ITN' to 'prop_house'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_individuals_ITN' to 'prop_indiv'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_ITN_use' to 'prop_ITN_u'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_individuals_slept_ITN' to 'prop_ind_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_households_ITN_2' to 'prop_hou_1'
  ogr_write(
C:\Users\roywaswa\AppData\Local\Temp\ipykernel_19936\46379431.py:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  mal_2020_selected.to_file('shp/malaria_2020_selected.shp', driver='ESRI Shapefile')
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DHSYEAR_hhm' to 'DHSYEAR_hh'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_shch' to 'total_coun'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'treat_src_yes' to 'treat_src_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'fever_rec_only treated nets' to 'fever_rec_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count_hh' to 'total_co_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_use_yes' to 'net_use_ye'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_mean' to 'hh_size_me'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'hh_size_sum' to 'hh_size_su'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'total_count' to 'total_co_2'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_only treated (itn) nets' to 'net_owned_'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'net_owned_did not sleep under a net' to 'net_owne_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_children_5' to 'prop_child'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_households_ITN' to 'prop_house'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_individuals_ITN' to 'prop_indiv'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_ITN_use' to 'prop_ITN_u'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_individuals_slept_ITN' to 'prop_ind_1'
  ogr_write(
c:\Users\roywaswa\AppData\Roaming\mamba\envs\dsa\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'prop_households_ITN_2' to 'prop_hou_1'
  ogr_write(